import React, { useState } from "react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { AlertTriangle, Bot } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { cn } from "@/lib/utils";

export type AttestationFeature =
  | "clinical_note"
  | "discharge_summary"
  | "differential_dx"
  | "icd_suggest"
  | "radiology_impression"
  | "voice_dictation"
  | "executive_digest"
  | "triage_assist"
  | "sepsis_screening"
  | "nabh_assistant";

interface Props {
  open: boolean;
  title: string;
  feature: AttestationFeature;
  sourceId?: string | null;
  hospitalId: string;
  aiOutput: Record<string, unknown>;
  previewContent: string;
  initialEditableText: string;
  editableLabel?: string;
  onAccept: (editedText: string) => void;
  onDiscard: () => void;
}

const AIAttestationModal: React.FC<Props> = ({
  open, title, feature, sourceId, hospitalId, aiOutput,
  previewContent, initialEditableText, editableLabel = "Editable Content",
  onAccept, onDiscard,
}) => {
  const [editedText, setEditedText] = useState(initialEditableText);
  const [attested, setAttested] = useState(false);
  const [saving, setSaving] = useState(false);

  const wasEdited = editedText.trim() !== initialEditableText.trim();

  const handleOpen = (isOpen: boolean) => {
    if (isOpen) {
      setEditedText(initialEditableText);
      setAttested(false);
    }
    if (!isOpen) onDiscard();
  };

  const handleAccept = async () => {
    if (!attested) return;
    setSaving(true);
    try {
      const { data: { user } } = await supabase.auth.getUser();
      await (supabase as any).from("ai_attestations").insert({
        hospital_id: hospitalId,
        feature,
        source_id: sourceId ?? null,
        ai_output: aiOutput,
        attested_by: user?.id ?? null,
        attested_at: new Date().toISOString(),
        edited_before_save: wasEdited,
        disclaimer_shown: true,
      });
    } catch (e) {
      console.warn("Attestation log failed (non-blocking):", e);
    }
    setSaving(false);
    onAccept(editedText);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpen}>
      <DialogContent className="max-w-2xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Bot className="h-4 w-4 text-primary" />
            {title}
          </DialogTitle>
        </DialogHeader>

        {/* Mandatory disclaimer banner */}
        <div className="flex items-start gap-3 p-3 bg-amber-50 border border-amber-300 rounded-lg shrink-0">
          <AlertTriangle className="h-4 w-4 text-amber-600 shrink-0 mt-0.5" />
          <p className="text-xs text-amber-800 leading-relaxed">
            <strong>AI-Generated Content Warning:</strong> This content was generated by AI. It is for
            clinical decision support only and is <strong>NOT</strong> a substitute for your professional
            judgment. Review and edit as needed before accepting.
          </p>
        </div>

        <div className="flex-1 overflow-y-auto space-y-3 min-h-0">
          {/* Read-only preview */}
          <div>
            <p className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider mb-1">
              AI Output Preview
            </p>
            <div className="border rounded-lg p-3 bg-muted/30 max-h-48 overflow-y-auto">
              <pre className="text-xs whitespace-pre-wrap font-sans text-foreground leading-relaxed">
                {previewContent}
              </pre>
            </div>
          </div>

          {/* Editable area */}
          <div>
            <p className="text-[10px] font-bold uppercase text-muted-foreground tracking-wider mb-1">
              {editableLabel}
              {wasEdited && <span className="ml-2 text-amber-600 font-medium">(Edited)</span>}
            </p>
            <textarea
              value={editedText}
              onChange={(e) => setEditedText(e.target.value)}
              rows={5}
              className={cn(
                "w-full border rounded-lg p-3 text-sm resize-none outline-none transition-colors",
                "focus:border-primary focus:ring-2 focus:ring-primary/10",
                wasEdited ? "border-amber-400 bg-amber-50/30" : "border-border bg-background"
              )}
            />
          </div>
        </div>

        {/* Attestation checkbox */}
        <div className="flex items-start gap-3 pt-2 shrink-0">
          <Checkbox
            id="attest-check"
            checked={attested}
            onCheckedChange={(v) => setAttested(!!v)}
          />
          <Label
            htmlFor="attest-check"
            className="text-xs leading-relaxed cursor-pointer text-foreground"
          >
            I have reviewed this AI-generated content, verified its clinical accuracy, and accept
            responsibility for its use in this patient's record.
          </Label>
        </div>

        <DialogFooter className="shrink-0">
          <Button variant="ghost" size="sm" onClick={onDiscard} disabled={saving}>
            Discard
          </Button>
          <Button
            size="sm"
            onClick={handleAccept}
            disabled={!attested || saving}
            className="bg-emerald-600 hover:bg-emerald-700"
          >
            {saving ? "Saving..." : "Accept & Save"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default AIAttestationModal;
